[package]
name = "tuneflow-desktop"
version = "3.0.0"
description = "TuneFlow - Featherweight Native Desktop GUI Shell for elderly music lovers and homelab streamers"
authors = ["tamld"]
license = "MIT"
repository = "https://github.com/tamld/tuneflow"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "tuneflow_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = ["tray-icon", "image-png"] }
tauri-plugin-log = "2"
dirs = "5.0"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
