plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tamld.tuneflow'
    compileSdk 34

    defaultConfig {
        applicationId "com.tamld.tuneflow"
        minSdk 24
        targetSdk 34
        versionCode 250
        versionName "2.5.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    flavorDimensions = ["deviceType"]
    productFlavors {
        mobile {
            dimension "deviceType"
            applicationIdSuffix ""
            versionNameSuffix "-mobile"
        }
        tv {
            dimension "deviceType"
            applicationIdSuffix ".tv"
            versionNameSuffix "-tv"
        }
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets']
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.10.0'
}
